config/routes.rb
Rails.application.routes.draw do
  resources :request_notifiers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/request_notifier.rb
class RequestNotifier < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/request_notifiers_controller.rb
class RequestNotifiersController < ApplicationController
  before_action :set_request_notifier, only: [:show, :edit, :update, :destroy]

  # GET /request_notifiers
  # GET /request_notifiers.json
  def index
    @request_notifiers = RequestNotifier.all
  end

  # GET /request_notifiers/1
  # GET /request_notifiers/1.json
  def show
  end

  # GET /request_notifiers/new
  def new
    @request_notifier = RequestNotifier.new
  end

  # GET /request_notifiers/1/edit
  def edit
  end

  # POST /request_notifiers
  # POST /request_notifiers.json
  def create
    @request_notifier = RequestNotifier.new(request_notifier_params)

    respond_to do |format|
      if @request_notifier.save
        format.html { redirect_to @request_notifier, notice: 'Request notifier was successfully created.' }
        format.json { render :show, status: :created, location: @request_notifier }
      else
        format.html { render :new }
        format.json { render json: @request_notifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /request_notifiers/1
  # PATCH/PUT /request_notifiers/1.json
  def update
    respond_to do |format|
      if @request_notifier.update(request_notifier_params)
        format.html { redirect_to @request_notifier, notice: 'Request notifier was successfully updated.' }
        format.json { render :show, status: :ok, location: @request_notifier }
      else
        format.html { render :edit }
        format.json { render json: @request_notifier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /request_notifiers/1
  # DELETE /request_notifiers/1.json
  def destroy
    @request_notifier.destroy
    respond_to do |format|
      format.html { redirect_to request_notifiers_url, notice: 'Request notifier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request_notifier
      @request_notifier = RequestNotifier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_notifier_params
      params.require(:request_notifier).permit(:todo_name, :urgency, :description, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/request_notifiers_helper.rb
module RequestNotifiersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoNotifier</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/request_notifiers/_form.html.erb
<%= form_with(model: request_notifier, local: true) do |form| %>
  <% if request_notifier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request_notifier.errors.count, "error") %> prohibited this request_notifier from being saved:</h2>

      <ul>
        <% request_notifier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :todo_name %>
    <%= form.text_field :todo_name %>
  </div>

  <div class="field">
    <%= form.label :urgency %>
    <%= form.text_field :urgency %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/request_notifiers/edit.html.erb
<h1>Editing Request Notifier</h1>

<%= render 'form', request_notifier: @request_notifier %>

<%= link_to 'Show', @request_notifier %> |
<%= link_to 'Back', request_notifiers_path %>

app/views/request_notifiers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Request Notifiers</h1>

<table>
  <thead>
    <tr>
      <th>Todo name</th>
      <th>Urgency</th>
      <th>Description</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @request_notifiers.each do |request_notifier| %>
      <tr>
        <td><%= request_notifier.todo_name %></td>
        <td><%= request_notifier.urgency %></td>
        <td><%= request_notifier.description %></td>
        <td><%= request_notifier.photo %></td>
        <td><%= link_to 'Show', request_notifier %></td>
        <td><%= link_to 'Edit', edit_request_notifier_path(request_notifier) %></td>
        <td><%= link_to 'Destroy', request_notifier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Request Notifier', new_request_notifier_path %>

app/views/request_notifiers/new.html.erb
<h1>New Request Notifier</h1>

<%= render 'form', request_notifier: @request_notifier %>

<%= link_to 'Back', request_notifiers_path %>

app/views/request_notifiers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Todo name:</strong>
  <%= @request_notifier.todo_name %>
</p>

<p>
  <strong>Urgency:</strong>
  <%= @request_notifier.urgency %>
</p>

<p>
  <strong>Description:</strong>
  <%= @request_notifier.description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @request_notifier.photo %>
</p>

<%= link_to 'Edit', edit_request_notifier_path(@request_notifier) %> |
<%= link_to 'Back', request_notifiers_path %>